const cards = [
  {
    title: 'Action (set A)',
    linkURL: '/actionA',
    categoryImage: './data/img/dance.jpg',
    cards: [
      {
        word: 'cry',
        translation: 'плакать',
        image: './data/img/cry.jpg',
        audio: './data/audio/cry.mp3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: './data/img/dance.jpg',
        audio: './data/audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: './data/img/dive.jpg',
        audio: './data/audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: './data/img/draw.jpg',
        audio: './data/audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: './data/img/fish.jpg',
        audio: './data/audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: './data/img/fly.jpg',
        audio: './data/audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: './data/img/hug.jpg',
        audio: './data/audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: './data/img/jump.jpg',
        audio: './data/audio/jump.mp3',
      },
    ],
  },
  {
    title: 'Action (set B)',
    linkURL: '/actionB',
    categoryImage: './data/img/run.jpg',
    cards: [
      {
        word: 'open',
        translation: 'открывать',
        image: './data/img/open.jpg',
        audio: './data/audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: './data/img/play.jpg',
        audio: './data/audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: './data/img/point.jpg',
        audio: './data/audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: './data/img/ride.jpg',
        audio: './data/audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: './data/img/run.jpg',
        audio: './data/audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: './data/img/sing.jpg',
        audio: './data/audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'пропускать, прыгать',
        image: './data/img/skip.jpg',
        audio: './data/audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: './data/img/swim.jpg',
        audio: './data/audio/swim.mp3',
      },
    ],
  },
  {
    title: 'Action (set C)',
    linkURL: '/actionC',
    categoryImage: './data/img/push.jpg',
    cards: [
      {
        word: 'argue',
        translation: 'спорить',
        image: './data/img/argue.jpg',
        audio: './data/audio/argue.mp3',
      },
      {
        word: 'build',
        translation: 'строить',
        image: './data/img/build.jpg',
        audio: './data/audio/build.mp3',
      },
      {
        word: 'carry',
        translation: 'нести',
        image: './data/img/carry.jpg',
        audio: './data/audio/carry.mp3',
      },
      {
        word: 'catch',
        translation: 'ловить',
        image: './data/img/catch.jpg',
        audio: './data/audio/catch.mp3',
      },
      {
        word: 'drive',
        translation: 'водить машину',
        image: './data/img/drive.jpg',
        audio: './data/audio/drive.mp3',
      },
      {
        word: 'drop',
        translation: 'падать',
        image: './data/img/drop.jpg',
        audio: './data/audio/drop.mp3',
      },
      {
        word: 'pull',
        translation: 'тянуть',
        image: './data/img/pull.jpg',
        audio: './data/audio/pull.mp3',
      },
      {
        word: 'push',
        translation: 'толкать',
        image: './data/img/push.jpg',
        audio: './data/audio/push.mp3',
      },
    ],
  },
  {
    title: 'Adjective',
    linkURL: '/adjective',
    categoryImage: './data/img/friendly.jpg',
    cards: [
      {
        word: 'big',
        translation: 'большой',
        image: './data/img/big.jpg',
        audio: './data/audio/big.mp3',
      },
      {
        word: 'small',
        translation: 'маленький',
        image: './data/img/small.jpg',
        audio: './data/audio/small.mp3',
      },
      {
        word: 'fast',
        translation: 'быстрый',
        image: './data/img/fast.jpg',
        audio: './data/audio/fast.mp3',
      },
      {
        word: 'slow',
        translation: 'медленный',
        image: './data/img/slow.jpg',
        audio: './data/audio/slow.mp3',
      },
      {
        word: 'friendly',
        translation: 'дружелюбный',
        image: './data/img/friendly.jpg',
        audio: './data/audio/friendly.mp3',
      },
      {
        word: 'unfriendly',
        translation: 'недружелюбный',
        image: './data/img/unfriendly.jpg',
        audio: './data/audio/unfriendly.mp3',
      },
      {
        word: 'young',
        translation: 'молодой',
        image: './data/img/young.jpg',
        audio: './data/audio/young.mp3',
      },
      {
        word: 'old',
        translation: 'старый',
        image: './data/img/old.jpg',
        audio: './data/audio/old.mp3',
      },
    ],
  },
  {
    title: 'Animal (set A)',
    linkURL: '/animalA',
    categoryImage: './data/img/cat.jpg',
    cards: [
      {
        word: 'cat',
        translation: 'кот',
        image: './data/img/cat.jpg',
        audio: './data/audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: './data/img/chick.jpg',
        audio: './data/audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: './data/img/chicken.jpg',
        audio: './data/audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: './data/img/dog.jpg',
        audio: './data/audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: './data/img/horse.jpg',
        audio: './data/audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: './data/img/pig.jpg',
        audio: './data/audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: './data/img/rabbit.jpg',
        audio: './data/audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: './data/img/sheep.jpg',
        audio: './data/audio/sheep.mp3',
      },
    ],
  },
  {
    title: 'Animal (set B)',
    linkURL: '/animalB',
    categoryImage: './data/img/lion.jpg',
    cards: [
      {
        word: 'bird',
        translation: 'птица',
        image: './data/img/bird.jpg',
        audio: './data/audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: './data/img/fish1.jpg',
        audio: './data/audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: './data/img/frog.jpg',
        audio: './data/audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: './data/img/giraffe.jpg',
        audio: './data/audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: './data/img/lion.jpg',
        audio: './data/audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: './data/img/mouse.jpg',
        audio: './data/audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: './data/img/turtle.jpg',
        audio: './data/audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: './data/img/dolphin.jpg',
        audio: './data/audio/dolphin.mp3',
      },
    ],
  },
  {
    title: 'Clothes',
    linkURL: '/clothes',
    categoryImage: './data/img/dress.jpg',
    cards: [
      {
        word: 'skirt',
        translation: 'юбка',
        image: './data/img/skirt.jpg',
        audio: './data/audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: './data/img/pants.jpg',
        audio: './data/audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: './data/img/blouse.jpg',
        audio: './data/audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: './data/img/dress.jpg',
        audio: './data/audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: './data/img/boot.jpg',
        audio: './data/audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: './data/img/shirt.jpg',
        audio: './data/audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: './data/img/coat.jpg',
        audio: './data/audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: './data/img/shoe.jpg',
        audio: './data/audio/shoe.mp3',
      },
    ],
  },
  {
    title: 'Emotions',
    linkURL: '/emotions',
    categoryImage: './data/img/happy.jpg',
    cards: [
      {
        word: 'sad',
        translation: 'грустный',
        image: './data/img/sad.jpg',
        audio: './data/audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: './data/img/angry.jpg',
        audio: './data/audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: './data/img/happy.jpg',
        audio: './data/audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: './data/img/tired.jpg',
        audio: './data/audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: './data/img/surprised.jpg',
        audio: './data/audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: './data/img/scared.jpg',
        audio: './data/audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: './data/img/smile.jpg',
        audio: './data/audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: './data/img/laugh.jpg',
        audio: './data/audio/laugh.mp3',
      },
    ],
  },
];

export default cards;
